[DEFAULT]
# the ip of the mobile device the game runs on
# could be the device's IP in the network or localhost (127.0.0.1)
deviceIp = 127.0.0.1
environment=local
platformName=android
deviceName=11231JEC200632
udid.10.182.6.106=00008101-001924E83EEB001E
udid.10.182.45.120=8d40e749d6ccce7bddc9b855161dd44e92e3f5a6
udid.10.182.45.115=00008101-000A30AC0C60001E
udid.10.182.45.121=00008020-001A3D2C36C2402E
#udid.10.182.6.106=00008101-001924E83EEB001E

deviceName_ios=Testing?s iPhone 8 plus
app=2152-BS01-QueensPuzzle-develop-v2.0.0.9371-da0d7e4ba-UAT_automation.apk
automationName=UiAutomator2
app.package=com.kwalee.queenspuzzle
android_app_activity=com.unity3d.player.UnityPlayerActivity
#android_no_reset = true
#android_full_reset = false
altUnityHost=alttester.kwalee.com
altUnityPort=13000
appName=queens
app.appBundleId=com.kwalee.queenspuzzle
START_LEVEL=95
LEVEL_COUNT=100
#server_hostname=dbc-f98adaea-933f.cloud.databricks.com
#http_path=/sql/1.0/warehouses/dec55c50d163369b
server_hostname=dbc-3de69967-09a0.cloud.databricks.com
http_path=/sql/1.0/warehouses/0504ac7484f73f71
access_token=

